export interface QuizQuestion {
  id: number
  question: string
  answers: [string, string, string, string]
  correct: 0 | 1 | 2 | 3
  explanation: string
  category: 'phat-giao' | 'cong-giao' | 'mac-lenin' | 'phap-luat'
  difficulty: 'easy' | 'medium' | 'hard'
}

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 1,
    question: 'Phật giáo du nhập vào Việt Nam từ khoảng thế kỷ nào?',
    answers: ['Thế kỷ I TCN', 'Thế kỷ II SCN', 'Thế kỷ III SCN', 'Thế kỷ IV SCN'],
    correct: 1,
    explanation: 'Phật giáo du nhập vào Việt Nam khoảng thế kỷ II SCN qua giao thương từ Ấn Độ. Luy Lâu (Bắc Ninh) là trung tâm Phật giáo đầu tiên.',
    category: 'phat-giao',
    difficulty: 'easy',
  },
  {
    id: 2,
    question: 'Giáo hội Phật giáo Việt Nam được thành lập năm nào?',
    answers: ['1975', '1978', '1981', '1986'],
    correct: 2,
    explanation: 'Giáo hội Phật giáo Việt Nam thành lập năm 1981 tại Hà Nội, thống nhất 9 tổ chức và hệ phái Phật giáo.',
    category: 'phat-giao',
    difficulty: 'easy',
  },
  {
    id: 3,
    question: 'Thiền phái Trúc Lâm Yên Tử do ai sáng lập?',
    answers: ['Trần Thái Tông', 'Trần Nhân Tông', 'Lý Thái Tổ', 'Trần Anh Tông'],
    correct: 1,
    explanation: 'Vua Trần Nhân Tông (1258–1308) sáng lập thiền phái Trúc Lâm Yên Tử — thiền phái thuần Việt đặc sắc. Ông được tôn là "Phật hoàng".',
    category: 'phat-giao',
    difficulty: 'medium',
  },
  {
    id: 4,
    question: 'Phương châm hoạt động của Giáo hội Phật giáo Việt Nam là?',
    answers: ['Từ bi, hỷ xả', 'Vô thường, vô ngã', 'Đạo pháp, dân tộc và CNXH', 'An lạc, giải thoát'],
    correct: 2,
    explanation: '"Đạo pháp, dân tộc và chủ nghĩa xã hội" — phương châm của GHPGVN thể hiện gắn bó đạo pháp với vận mệnh đất nước.',
    category: 'phat-giao',
    difficulty: 'easy',
  },
  {
    id: 5,
    question: 'Theo sử liệu, Công giáo chính thức du nhập Việt Nam năm nào?',
    answers: ['1513', '1527', '1533', '1627'],
    correct: 2,
    explanation: 'Năm 1533, giáo sĩ I-nê-khu vào Ninh Cường và Trà Lũ (Nam Định) truyền đạo — mốc ghi nhận Công giáo du nhập Việt Nam.',
    category: 'cong-giao',
    difficulty: 'medium',
  },
  {
    id: 6,
    question: 'Ai biên soạn từ điển Việt-Bồ-La (1651), đặt nền tảng chữ Quốc ngữ?',
    answers: ["Francisco de Pina", "Gaspar d'Amaral", 'Alexandre de Rhodes', 'Pigneau de Béhaine'],
    correct: 2,
    explanation: 'Alexandre de Rhodes (Đắc Lộ, 1593–1660) biên soạn từ điển Việt-Bồ-La và sách giáo lý chữ Quốc ngữ xuất bản tại Rome, 1651.',
    category: 'cong-giao',
    difficulty: 'medium',
  },
  {
    id: 7,
    question: 'Đường hướng của Giáo hội Công giáo Việt Nam từ năm 1980 là?',
    answers: ['Kính Chúa yêu nước', 'Sống Phúc âm giữa lòng dân tộc', 'Phụng sự Thiên Chúa và Tổ quốc', 'Hòa bình và công lý'],
    correct: 1,
    explanation: 'HĐGM Việt Nam năm 1980 công bố đường hướng "Sống Phúc âm giữa lòng dân tộc" — gắn kết đức tin Công giáo với lòng yêu nước.',
    category: 'cong-giao',
    difficulty: 'easy',
  },
  {
    id: 8,
    question: 'Theo chủ nghĩa Mác-Lênin, tôn giáo có mấy nguồn gốc cơ bản?',
    answers: ['2 nguồn gốc', '3 nguồn gốc', '4 nguồn gốc', '5 nguồn gốc'],
    correct: 1,
    explanation: 'Tôn giáo có 3 nguồn gốc: (1) Xã hội — bất lực trước tự nhiên/xã hội; (2) Nhận thức — tuyệt đối hóa nhận thức; (3) Tâm lý — sợ hãi, cầu an.',
    category: 'mac-lenin',
    difficulty: 'medium',
  },
  {
    id: 9,
    question: 'Tính chất nào KHÔNG phải là tính chất cơ bản của tôn giáo theo Mác-Lênin?',
    answers: ['Tính quần chúng', 'Tính chính trị', 'Tính kinh tế', 'Tính đạo đức'],
    correct: 2,
    explanation: 'Tôn giáo có 3 tính chất: quần chúng (tín đồ đông đảo), chính trị (phản ánh đấu tranh giai cấp), đạo đức (giá trị nhân bản). Không có "tính kinh tế".',
    category: 'mac-lenin',
    difficulty: 'hard',
  },
  {
    id: 10,
    question: 'Luật Tín ngưỡng, tôn giáo Việt Nam được Quốc hội thông qua năm nào?',
    answers: ['2012', '2014', '2016', '2018'],
    correct: 2,
    explanation: 'Luật Tín ngưỡng, tôn giáo thông qua ngày 18/11/2016, hiệu lực từ 01/01/2018, thay thế Pháp lệnh tín ngưỡng, tôn giáo 2004.',
    category: 'phap-luat',
    difficulty: 'medium',
  },
  {
    id: 11,
    question: 'Vua Trần Nhân Tông được phong tôn danh gì trong Phật giáo Việt Nam?',
    answers: ['Pháp vương', 'Phật hoàng', 'Đại thiền sư', 'Hộ pháp'],
    correct: 1,
    explanation: 'Trần Nhân Tông được tôn là "Phật hoàng" — hoàng đế duy nhất Đông Nam Á xuất gia đắc đạo và khai sáng thiền phái Trúc Lâm.',
    category: 'phat-giao',
    difficulty: 'easy',
  },
  {
    id: 12,
    question: 'Điều 24 Hiến pháp 2013 quy định điều gì về tôn giáo?',
    answers: [
      'Nhà nước bảo hộ một tôn giáo chính thống',
      'Mọi người có quyền tự do tín ngưỡng, tôn giáo',
      'Hoạt động tôn giáo chỉ được trong cơ sở tôn giáo',
      'Chỉ công dân được theo tôn giáo',
    ],
    correct: 1,
    explanation: 'Điều 24: "Mọi người có quyền tự do tín ngưỡng, tôn giáo, theo hoặc không theo một tôn giáo nào. Các tôn giáo bình đẳng trước pháp luật."',
    category: 'phap-luat',
    difficulty: 'easy',
  },
  {
    id: 13,
    question: "Phong trào 'Phật giáo đồng hành cùng dân tộc' thể hiện điều gì?",
    answers: [
      'Phật giáo tách biệt khỏi chính trị',
      'Phật giáo gắn bó với vận mệnh đất nước qua các thời đại',
      'Phật giáo chỉ chú trọng tu tập',
      'Phật giáo phản đối mọi chính quyền',
    ],
    correct: 1,
    explanation: 'Suốt lịch sử, Phật giáo luôn đồng hành cùng dân tộc: từ chống Bắc thuộc, đánh Mông-Nguyên, đến kháng Pháp và xây dựng đất nước.',
    category: 'phat-giao',
    difficulty: 'easy',
  },
  {
    id: 14,
    question: 'Thừa sai Công giáo đầu tiên tại Việt Nam (TK XVI–XVII) đến từ đâu?',
    answers: ['Tây Ban Nha', 'Pháp', 'Ý (La Mã)', 'Bồ Đào Nha'],
    correct: 3,
    explanation: 'Các thừa sai Dòng Tên (Jesuit) đầu tiên ở Việt Nam là người Bồ Đào Nha, trong khuôn khổ quyền bảo trợ truyền giáo của Bồ Đào Nha (Padroado).',
    category: 'cong-giao',
    difficulty: 'hard',
  },
  {
    id: 15,
    question: 'Theo Lênin, tôn giáo là gì đối với nhà nước vô sản?',
    answers: [
      'Là công cụ quản lý xã hội',
      'Là việc riêng tư của mỗi cá nhân',
      'Là kẻ thù cần xóa bỏ ngay',
      'Là nền tảng đạo đức quốc gia',
    ],
    correct: 1,
    explanation: 'Lênin: tôn giáo là "việc riêng" đối với nhà nước — không can thiệp tín ngưỡng cá nhân, nhưng đấu tranh chống mê tín và lợi dụng tôn giáo.',
    category: 'mac-lenin',
    difficulty: 'medium',
  },
  {
    id: 16,
    question: 'Đóng góp văn hóa quan trọng nhất của Công giáo với Việt Nam là?',
    answers: [
      'Xây dựng hệ thống nhà thờ',
      'Góp phần hình thành và phổ biến chữ Quốc ngữ',
      'Đưa kỹ thuật in ấn vào VN',
      'Lập hệ thống trường học',
    ],
    correct: 1,
    explanation: 'Chữ Quốc ngữ — do giáo sĩ sáng tạo, Alexandre de Rhodes hệ thống hóa (1651) — là đóng góp văn hóa vĩ đại nhất của Công giáo với Việt Nam.',
    category: 'cong-giao',
    difficulty: 'easy',
  },
  {
    id: 17,
    question: 'Nguyên tắc đúng giải quyết vấn đề tôn giáo theo Mác-Lênin là?',
    answers: [
      'Dùng biện pháp hành chính xóa bỏ tôn giáo',
      'Tôn trọng tự do tín ngưỡng và phân biệt sinh hoạt tôn giáo với lợi dụng tôn giáo',
      'Chỉ cho phép một tôn giáo',
      'Nhà nước kiểm soát toàn bộ tôn giáo',
    ],
    correct: 1,
    explanation: 'Mác-Lênin: tôn trọng tự do tín ngưỡng; phân biệt nhu cầu chính đáng với lợi dụng tôn giáo; đấu tranh chống mê tín và tôn giáo phản động.',
    category: 'mac-lenin',
    difficulty: 'medium',
  },
  {
    id: 18,
    question: 'Phật giáo truyền vào Việt Nam chủ yếu qua con đường nào?',
    answers: [
      'Chỉ qua Trung Quốc',
      'Trực tiếp từ Ấn Độ và gián tiếp qua Trung Quốc',
      'Từ Thái Lan và Myanmar',
      'Do nhà sư Nhật Bản mang đến',
    ],
    correct: 1,
    explanation: 'Phật giáo vào VN qua 2 con đường: trực tiếp từ Ấn Độ theo đường biển (sớm, dân gian) và gián tiếp qua Trung Quốc (phổ biến, Thiền tông).',
    category: 'phat-giao',
    difficulty: 'medium',
  },
  {
    id: 19,
    question: 'Trong kháng chiến chống Pháp, vai trò của Phật giáo Việt Nam là?',
    answers: [
      'Hợp tác với thực dân Pháp',
      'Nhiều tăng ni, tín đồ tích cực tham gia kháng chiến',
      'Chỉ hoạt động thuần túy tôn giáo',
      'Di tản ra nước ngoài',
    ],
    correct: 1,
    explanation: 'Tăng ni, tín đồ Phật giáo đông đảo tham gia kháng chiến chống Pháp, nhiều chùa là cơ sở cách mạng — tiếp nối truyền thống "đồng hành cùng dân tộc".',
    category: 'phat-giao',
    difficulty: 'easy',
  },
  {
    id: 20,
    question: 'Sắc lệnh 234 (1955) của Chủ tịch Hồ Chí Minh quy định điều gì?',
    answers: [
      'Quốc hữu hóa tài sản tôn giáo',
      'Đảm bảo tự do tín ngưỡng và tôn giáo cho nhân dân',
      'Bắt buộc người dân phải vô thần',
      'Cấm hoạt động truyền đạo',
    ],
    correct: 1,
    explanation: 'Sắc lệnh 234/SL (14/6/1955) là văn bản pháp lý quan trọng đảm bảo quyền tự do tín ngưỡng, tôn giáo — thể hiện chính sách tôn trọng tôn giáo của Nhà nước VN.',
    category: 'phap-luat',
    difficulty: 'hard',
  },
]
