export interface QuizQuestion {
  id: number
  question: string
  answers: [string, string, string, string]
  correct: 0 | 1 | 2 | 3
  explanation: string
  category: 'phat-giao' | 'cong-giao' | 'mac-lenin' | 'phap-luat'
  difficulty: 'easy' | 'medium' | 'hard'
}

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 1,
    question: 'Phật giáo du nhập vào Việt Nam từ khoảng thế kỷ nào?',
    answers: ['Thế kỷ I TCN', 'Thế kỷ II SCN', 'Thế kỷ III SCN', 'Thế kỷ IV SCN'],
    correct: 1,
    explanation: 'Phật giáo du nhập vào Việt Nam khoảng thế kỷ II SCN qua giao thương từ Ấn Độ. Luy Lâu (Bắc Ninh) là trung tâm Phật giáo đầu tiên.',
    category: 'phat-giao',
    difficulty: 'easy',
  },
  {
    id: 2,
    question: 'Giáo hội Phật giáo Việt Nam được thành lập năm nào?',
    answers: ['1975', '1978', '1981', '1986'],
    correct: 2,
    explanation: 'Giáo hội Phật giáo Việt Nam thành lập năm 1981 tại Hà Nội, thống nhất 9 tổ chức và hệ phái Phật giáo.',
    category: 'phat-giao',
    difficulty: 'easy',
  },
  {
    id: 3,
    question: 'Thiền phái Trúc Lâm Yên Tử do ai sáng lập?',
    answers: ['Trần Thái Tông', 'Trần Nhân Tông', 'Lý Thái Tổ', 'Trần Anh Tông'],
    correct: 1,
    explanation: 'Vua Trần Nhân Tông (1258–1308) sáng lập thiền phái Trúc Lâm Yên Tử — thiền phái thuần Việt đặc sắc. Ông được tôn là "Phật hoàng".',
    category: 'phat-giao',
    difficulty: 'medium',
  },
  {
    id: 4,
    question: 'Phương châm hoạt động của Giáo hội Phật giáo Việt Nam là?',
    answers: ['Từ bi, hỷ xả', 'Vô thường, vô ngã', 'Đạo pháp, dân tộc và CNXH', 'An lạc, giải thoát'],
    correct: 2,
    explanation: '"Đạo pháp, dân tộc và chủ nghĩa xã hội" — phương châm của GHPGVN thể hiện gắn bó đạo pháp với vận mệnh đất nước.',
    category: 'phat-giao',
    difficulty: 'easy',
  },
  {
    id: 5,
    question: 'Theo sử liệu, Công giáo chính thức du nhập Việt Nam năm nào?',
    answers: ['1513', '1527', '1533', '1627'],
    correct: 2,
    explanation: 'Năm 1533, giáo sĩ I-nê-khu vào Ninh Cường và Trà Lũ (Nam Định) truyền đạo — mốc ghi nhận Công giáo du nhập Việt Nam.',
    category: 'cong-giao',
    difficulty: 'medium',
  },
  {
    id: 6,
    question: 'Ai biên soạn từ điển Việt-Bồ-La (1651), đặt nền tảng chữ Quốc ngữ?',
    answers: ["Francisco de Pina", "Gaspar d'Amaral", 'Alexandre de Rhodes', 'Pigneau de Béhaine'],
    correct: 2,
    explanation: 'Alexandre de Rhodes (Đắc Lộ, 1593–1660) biên soạn từ điển Việt-Bồ-La và sách giáo lý chữ Quốc ngữ xuất bản tại Rome, 1651.',
    category: 'cong-giao',
    difficulty: 'medium',
  },
  {
    id: 7,
    question: 'Đường hướng của Giáo hội Công giáo Việt Nam từ năm 1980 là?',
    answers: ['Kính Chúa yêu nước', 'Sống Phúc âm giữa lòng dân tộc', 'Phụng sự Thiên Chúa và Tổ quốc', 'Hòa bình và công lý'],
    correct: 1,
    explanation: 'HĐGM Việt Nam năm 1980 công bố đường hướng "Sống Phúc âm giữa lòng dân tộc" — gắn kết đức tin Công giáo với lòng yêu nước.',
    category: 'cong-giao',
    difficulty: 'easy',
  },
  {
    id: 8,
    question: 'Theo chủ nghĩa Mác-Lênin, tôn giáo có mấy nguồn gốc cơ bản?',
    answers: ['2 nguồn gốc', '3 nguồn gốc', '4 nguồn gốc', '5 nguồn gốc'],
    correct: 1,
    explanation: 'Tôn giáo có 3 nguồn gốc: (1) Xã hội — bất lực trước tự nhiên/xã hội; (2) Nhận thức — tuyệt đối hóa nhận thức; (3) Tâm lý — sợ hãi, cầu an.',
    category: 'mac-lenin',
    difficulty: 'medium',
  },
  {
    id: 9,
    question: 'Tính chất nào KHÔNG phải là tính chất cơ bản của tôn giáo theo Mác-Lênin?',
    answers: ['Tính quần chúng', 'Tính chính trị', 'Tính kinh tế', 'Tính đạo đức'],
    correct: 2,
    explanation: 'Tôn giáo có 3 tính chất: quần chúng (tín đồ đông đảo), chính trị (phản ánh đấu tranh giai cấp), đạo đức (giá trị nhân bản). Không có "tính kinh tế".',
    category: 'mac-lenin',
    difficulty: 'hard',
  },
  {
    id: 10,
    question: 'Luật Tín ngưỡng, tôn giáo Việt Nam được Quốc hội thông qua năm nào?',
    answers: ['2012', '2014', '2016', '2018'],
    correct: 2,
    explanation: 'Luật Tín ngưỡng, tôn giáo thông qua ngày 18/11/2016, hiệu lực từ 01/01/2018, thay thế Pháp lệnh tín ngưỡng, tôn giáo 2004.',
    category: 'phap-luat',
    difficulty: 'medium',
  },
  {
    id: 11,
    question: 'Vua Trần Nhân Tông được phong tôn danh gì trong Phật giáo Việt Nam?',
    answers: ['Pháp vương', 'Phật hoàng', 'Đại thiền sư', 'Hộ pháp'],
    correct: 1,
    explanation: 'Trần Nhân Tông được tôn là "Phật hoàng" — hoàng đế duy nhất Đông Nam Á xuất gia đắc đạo và khai sáng thiền phái Trúc Lâm.',
    category: 'phat-giao',
    difficulty: 'easy',
  },
  {
    id: 12,
    question: 'Điều 24 Hiến pháp 2013 quy định điều gì về tôn giáo?',
    answers: [
      'Nhà nước bảo hộ một tôn giáo chính thống',
      'Mọi người có quyền tự do tín ngưỡng, tôn giáo',
      'Hoạt động tôn giáo chỉ được trong cơ sở tôn giáo',
      'Chỉ công dân được theo tôn giáo',
    ],
    correct: 1,
    explanation: 'Điều 24: "Mọi người có quyền tự do tín ngưỡng, tôn giáo, theo hoặc không theo một tôn giáo nào. Các tôn giáo bình đẳng trước pháp luật."',
    category: 'phap-luat',
    difficulty: 'easy',
  },
  {
    id: 13,
    question: "Phong trào 'Phật giáo đồng hành cùng dân tộc' thể hiện điều gì?",
    answers: [
      'Phật giáo tách biệt khỏi chính trị',
      'Phật giáo gắn bó với vận mệnh đất nước qua các thời đại',
      'Phật giáo chỉ chú trọng tu tập',
      'Phật giáo phản đối mọi chính quyền',
    ],
    correct: 1,
    explanation: 'Suốt lịch sử, Phật giáo luôn đồng hành cùng dân tộc: từ chống Bắc thuộc, đánh Mông-Nguyên, đến kháng Pháp và xây dựng đất nước.',
    category: 'phat-giao',
    difficulty: 'easy',
  },
  {
    id: 14,
    question: 'Thừa sai Công giáo đầu tiên tại Việt Nam (TK XVI–XVII) đến từ đâu?',
    answers: ['Tây Ban Nha', 'Pháp', 'Ý (La Mã)', 'Bồ Đào Nha'],
    correct: 3,
    explanation: 'Các thừa sai Dòng Tên (Jesuit) đầu tiên ở Việt Nam là người Bồ Đào Nha, trong khuôn khổ quyền bảo trợ truyền giáo của Bồ Đào Nha (Padroado).',
    category: 'cong-giao',
    difficulty: 'hard',
  },
  {
    id: 15,
    question: 'Theo Lênin, tôn giáo là gì đối với nhà nước vô sản?',
    answers: [
      'Là công cụ quản lý xã hội',
      'Là việc riêng tư của mỗi cá nhân',
      'Là kẻ thù cần xóa bỏ ngay',
      'Là nền tảng đạo đức quốc gia',
    ],
    correct: 1,
    explanation: 'Lênin: tôn giáo là "việc riêng" đối với nhà nước — không can thiệp tín ngưỡng cá nhân, nhưng đấu tranh chống mê tín và lợi dụng tôn giáo.',
    category: 'mac-lenin',
    difficulty: 'medium',
  },
  {
    id: 16,
    question: 'Đóng góp văn hóa quan trọng nhất của Công giáo với Việt Nam là?',
    answers: [
      'Xây dựng hệ thống nhà thờ',
      'Góp phần hình thành và phổ biến chữ Quốc ngữ',
      'Đưa kỹ thuật in ấn vào VN',
      'Lập hệ thống trường học',
    ],
    correct: 1,
    explanation: 'Chữ Quốc ngữ — do giáo sĩ sáng tạo, Alexandre de Rhodes hệ thống hóa (1651) — là đóng góp văn hóa vĩ đại nhất của Công giáo với Việt Nam.',
    category: 'cong-giao',
    difficulty: 'easy',
  },
  {
    id: 17,
    question: 'Nguyên tắc đúng giải quyết vấn đề tôn giáo theo Mác-Lênin là?',
    answers: [
      'Dùng biện pháp hành chính xóa bỏ tôn giáo',
      'Tôn trọng tự do tín ngưỡng và phân biệt sinh hoạt tôn giáo với lợi dụng tôn giáo',
      'Chỉ cho phép một tôn giáo',
      'Nhà nước kiểm soát toàn bộ tôn giáo',
    ],
    correct: 1,
    explanation: 'Mác-Lênin: tôn trọng tự do tín ngưỡng; phân biệt nhu cầu chính đáng với lợi dụng tôn giáo; đấu tranh chống mê tín và tôn giáo phản động.',
    category: 'mac-lenin',
    difficulty: 'medium',
  },
  {
    id: 18,
    question: 'Phật giáo truyền vào Việt Nam chủ yếu qua con đường nào?',
    answers: [
      'Chỉ qua Trung Quốc',
      'Trực tiếp từ Ấn Độ và gián tiếp qua Trung Quốc',
      'Từ Thái Lan và Myanmar',
      'Do nhà sư Nhật Bản mang đến',
    ],
    correct: 1,
    explanation: 'Phật giáo vào VN qua 2 con đường: trực tiếp từ Ấn Độ theo đường biển (sớm, dân gian) và gián tiếp qua Trung Quốc (phổ biến, Thiền tông).',
    category: 'phat-giao',
    difficulty: 'medium',
  },
  {
    id: 19,
    question: 'Trong kháng chiến chống Pháp, vai trò của Phật giáo Việt Nam là?',
    answers: [
      'Hợp tác với thực dân Pháp',
      'Nhiều tăng ni, tín đồ tích cực tham gia kháng chiến',
      'Chỉ hoạt động thuần túy tôn giáo',
      'Di tản ra nước ngoài',
    ],
    correct: 1,
    explanation: 'Tăng ni, tín đồ Phật giáo đông đảo tham gia kháng chiến chống Pháp, nhiều chùa là cơ sở cách mạng — tiếp nối truyền thống "đồng hành cùng dân tộc".',
    category: 'phat-giao',
    difficulty: 'easy',
  },
  {
    id: 20,
    question: 'Sắc lệnh 234 (1955) của Chủ tịch Hồ Chí Minh quy định điều gì?',
    answers: [
      'Quốc hữu hóa tài sản tôn giáo',
      'Đảm bảo tự do tín ngưỡng và tôn giáo cho nhân dân',
      'Bắt buộc người dân phải vô thần',
      'Cấm hoạt động truyền đạo',
    ],
    correct: 1,
    explanation: 'Sắc lệnh 234/SL (14/6/1955) là văn bản pháp lý quan trọng đảm bảo quyền tự do tín ngưỡng, tôn giáo — thể hiện chính sách tôn trọng tôn giáo của Nhà nước VN.',
    category: 'phap-luat',
    difficulty: 'hard',
  },
  // --- 40 câu bổ sung ---
  {
    id: 21,
    question: 'Tứ Diệu Đế (Catvāri Āryasatyāni) bao gồm những gì?',
    answers: ['Khổ, Tập, Diệt, Đạo', 'Sinh, Lão, Bệnh, Tử', 'Sắc, Thọ, Tưởng, Hành', 'Tham, Sân, Si, Mạn'],
    correct: 0,
    explanation: 'Tứ Diệu Đế: Khổ đế (sự khổ), Tập đế (nguyên nhân khổ), Diệt đế (diệt khổ) và Đạo đế (con đường diệt khổ) — nền tảng giáo lý Phật giáo.',
    category: 'phat-giao',
    difficulty: 'medium',
  },
  {
    id: 22,
    question: 'Bát Chánh Đạo trong Phật giáo có bao nhiêu yếu tố?',
    answers: ['6', '7', '8', '10'],
    correct: 2,
    explanation: 'Bát Chánh Đạo gồm 8 yếu tố: Chánh kiến, Chánh tư duy, Chánh ngữ, Chánh nghiệp, Chánh mệnh, Chánh tinh tấn, Chánh niệm, Chánh định.',
    category: 'phat-giao',
    difficulty: 'easy',
  },
  {
    id: 23,
    question: 'Chùa Một Cột ở Hà Nội được xây dựng dưới thời vua nào?',
    answers: ['Lý Thái Tổ', 'Lý Thái Tông', 'Lý Nhân Tông', 'Lý Anh Tông'],
    correct: 1,
    explanation: 'Chùa Một Cột (Liên Hoa Đài) xây năm 1049 dưới thời Lý Thái Tông, theo giấc mộng vua thấy Phật Quan Âm dẫn lên đài sen.',
    category: 'phat-giao',
    difficulty: 'medium',
  },
  {
    id: 24,
    question: 'Tam Tạng kinh điển Phật giáo (Tipitaka) gồm những tạng nào?',
    answers: ['Kinh, Luật, Luận', 'Kinh, Kệ, Chú', 'Sắc, Thanh, Hương', 'Giới, Định, Tuệ'],
    correct: 0,
    explanation: 'Tam Tạng gồm: Kinh tạng (lời Phật dạy), Luật tạng (giới luật) và Luận tạng (luận giải giáo lý) — toàn bộ kinh điển Phật giáo.',
    category: 'phat-giao',
    difficulty: 'medium',
  },
  {
    id: 25,
    question: 'Phật giáo Hòa Hảo do ai sáng lập và vào năm nào?',
    answers: ['Huỳnh Phú Sổ, 1939', 'Ngô Minh Chiêu, 1920', 'Lê Văn Trung, 1926', 'Phạm Công Tắc, 1935'],
    correct: 0,
    explanation: 'Phật giáo Hòa Hảo do Huỳnh Phú Sổ sáng lập năm 1939 tại làng Hòa Hảo (An Giang), phát triển mạnh ở miền Tây Nam Bộ với khoảng 1,3 triệu tín đồ.',
    category: 'phat-giao',
    difficulty: 'medium',
  },
  {
    id: 26,
    question: 'Thiền tông chính thức du nhập Việt Nam vào thế kỷ mấy?',
    answers: ['Thế kỷ V', 'Thế kỷ VI', 'Thế kỷ VII', 'Thế kỷ IX'],
    correct: 1,
    explanation: 'Thiền tông du nhập VN thế kỷ VI (580 SCN) khi thiền sư Tỳ-ni-đa-lưu-chi từ Ấn Độ qua Trung Quốc đến. Đây là thiền phái đầu tiên ở VN.',
    category: 'phat-giao',
    difficulty: 'hard',
  },
  {
    id: 27,
    question: '"Tam quy" trong Phật giáo là quy y những gì?',
    answers: ['Phật, Pháp, Tăng', 'Kinh, Luật, Luận', 'Giới, Định, Tuệ', 'Tín, Nguyện, Hạnh'],
    correct: 0,
    explanation: 'Tam quy là quy y Tam Bảo: Phật (giác ngộ), Pháp (giáo lý), Tăng (cộng đồng tu sĩ) — nghi thức căn bản nhất của người theo Phật.',
    category: 'phat-giao',
    difficulty: 'easy',
  },
  {
    id: 28,
    question: 'Đại lễ Phật Đản (Vesak) kỷ niệm sự kiện gì?',
    answers: [
      'Phật nhập Niết Bàn',
      'Phật đản sinh, thành đạo và nhập Niết Bàn',
      'Phật thành đạo tại Bồ Đề Đạo Tràng',
      'Phật chuyển pháp luân lần đầu',
    ],
    correct: 1,
    explanation: 'Đại lễ Vesak (rằm tháng Tư âm lịch) kỷ niệm cả 3 sự kiện: Phật đản sinh, thành đạo và nhập Niết Bàn — được LHQ công nhận là ngày lễ quốc tế.',
    category: 'phat-giao',
    difficulty: 'medium',
  },
  {
    id: 29,
    question: 'Tịnh Độ tông trong Phật giáo Việt Nam thờ ai là đối tượng chính?',
    answers: ['Phật Thích Ca', 'Phật A Di Đà', 'Bồ tát Quan Âm', 'Phật Di Lặc'],
    correct: 1,
    explanation: 'Tịnh Độ tông thờ Phật A Di Đà — niệm "Nam mô A Di Đà Phật" để vãng sinh Tây Phương Cực Lạc. Đây là hệ phái phổ biến nhất ở Việt Nam hiện nay.',
    category: 'phat-giao',
    difficulty: 'medium',
  },
  {
    id: 30,
    question: 'Chùa Trấn Quốc (Hà Nội) được xây dựng từ thế kỷ nào?',
    answers: ['Thế kỷ III', 'Thế kỷ VI', 'Thế kỷ X', 'Thế kỷ XV'],
    correct: 1,
    explanation: 'Chùa Trấn Quốc xây dựng từ thế kỷ VI (thời Lý Nam Đế, ~545 SCN) — một trong những ngôi chùa cổ nhất Việt Nam, khoảng 1500 năm lịch sử.',
    category: 'phat-giao',
    difficulty: 'hard',
  },
  {
    id: 31,
    question: 'Luận điểm "Phật tại tâm" trong Phật giáo Việt Nam phản ánh điều gì?',
    answers: [
      'Phật chỉ tồn tại trong tâm tưởng, không có thật',
      'Giác ngộ có thể đạt được từ nội tâm, không nhất thiết phải xuất gia',
      'Phật không cần chùa chiền',
      'Người tu tại gia cao hơn xuất gia',
    ],
    correct: 1,
    explanation: '"Phật tại tâm" phản ánh xu hướng Phật giáo nhập thế VN: giác ngộ không chỉ dành cho người xuất gia mà cả cư sĩ — tinh thần thiền phái Trúc Lâm Yên Tử.',
    category: 'phat-giao',
    difficulty: 'medium',
  },
  {
    id: 32,
    question: 'Phong trào chấn hưng Phật giáo Việt Nam đầu thế kỷ XX do ai khởi xướng?',
    answers: ['HT Khánh Hòa & HT Thiện Chiếu', 'HT Trí Thủ', 'HT Thích Minh Châu', 'HT Thích Nhất Hạnh'],
    correct: 0,
    explanation: 'Phong trào chấn hưng Phật giáo (1920–30s) do HT Khánh Hòa và HT Thiện Chiếu khởi xướng ở Nam Kỳ, nhằm canh tân, giáo dục và in ấn kinh sách Phật giáo.',
    category: 'phat-giao',
    difficulty: 'hard',
  },
  {
    id: 33,
    question: 'Thiền phái Liễu Quán tại Việt Nam do ai sáng lập?',
    answers: ['Thiền sư Liễu Quán', 'Thiền sư Minh Hải', 'Thiền sư Nguyên Thiều', 'Thiền sư Hương Hải'],
    correct: 0,
    explanation: 'Thiền sư Liễu Quán (1670–1742) sáng lập dòng thiền Liễu Quán ở miền Trung VN — dòng thiền người Việt hoàn toàn, độc lập với các dòng thiền Trung Quốc.',
    category: 'phat-giao',
    difficulty: 'hard',
  },
  {
    id: 34,
    question: 'Trong kháng chiến chống Mỹ, phong trào Phật giáo năm 1963 có sự kiện đặc biệt nào?',
    answers: [
      'Phật giáo tuyên bố trung lập',
      'Hòa thượng Thích Quảng Đức tự thiêu phản đối chính sách của Diệm',
      'Phật giáo thống nhất với Công giáo',
      'GHPGVN thành lập ở miền Nam',
    ],
    correct: 1,
    explanation: 'Ngày 11/6/1963, HT Thích Quảng Đức tự thiêu tại Sài Gòn phản đối chính sách đàn áp Phật giáo của chính quyền Ngô Đình Diệm — sự kiện chấn động thế giới.',
    category: 'phat-giao',
    difficulty: 'medium',
  },
  {
    id: 35,
    question: 'Số lượng tăng ni Phật giáo Việt Nam hiện nay (2023) khoảng bao nhiêu?',
    answers: ['20.000', '40.000', '60.000', '100.000'],
    correct: 2,
    explanation: 'GHPGVN hiện có khoảng 60.000 tăng ni, hơn 18.000 tự viện; gần 14 triệu tín đồ — một trong những quốc gia Phật giáo lớn ở châu Á.',
    category: 'phat-giao',
    difficulty: 'hard',
  },
  // Công giáo mở rộng
  {
    id: 36,
    question: 'Tòa Thánh Vatican có diện tích khoảng bao nhiêu km²?',
    answers: ['0,2 km²', '0,44 km²', '1,2 km²', '2,5 km²'],
    correct: 1,
    explanation: 'Vatican có diện tích 0,44 km² — quốc gia nhỏ nhất thế giới, trung tâm của Giáo hội Công giáo La Mã với hơn 1,3 tỷ tín đồ toàn cầu.',
    category: 'cong-giao',
    difficulty: 'medium',
  },
  {
    id: 37,
    question: 'Hội đồng Giám mục Việt Nam (HĐGMVN) được thành lập năm nào?',
    answers: ['1945', '1960', '1975', '1980'],
    correct: 1,
    explanation: 'HĐGMVN thành lập năm 1960 khi Tòa Thánh thiết lập hàng giáo phẩm chính thức tại VN với ba giáo tỉnh: Hà Nội, Huế và Sài Gòn.',
    category: 'cong-giao',
    difficulty: 'medium',
  },
  {
    id: 38,
    question: 'Công đồng Vatican II (1962–1965) thay đổi điều gì quan trọng nhất?',
    answers: [
      'Tăng quyền lực Giáo hoàng',
      'Cho phép dâng lễ bằng tiếng địa phương thay vì tiếng Latin',
      'Bãi bỏ chế độ độc thân linh mục',
      'Thống nhất với Chính Thống giáo',
    ],
    correct: 1,
    explanation: 'Vatican II cải cách phụng vụ cho phép dâng lễ bằng tiếng địa phương, mở ra đối thoại liên tôn và nhấn mạnh vai trò của giáo dân — cuộc cải cách lớn nhất thế kỷ XX.',
    category: 'cong-giao',
    difficulty: 'medium',
  },
  {
    id: 39,
    question: 'Nhà thờ Đức Bà Sài Gòn hoàn thành năm nào?',
    answers: ['1863', '1877', '1880', '1895'],
    correct: 2,
    explanation: 'Nhà thờ Đức Bà Sài Gòn khởi công 1877, hoàn thành 1880. Hai tháp chuông 57m thêm vào 1895 — biểu tượng kiến trúc Gothic của Sài Gòn.',
    category: 'cong-giao',
    difficulty: 'medium',
  },
  {
    id: 40,
    question: 'Giám mục người Việt Nam đầu tiên là ai?',
    answers: ['Nguyễn Bá Tòng', 'Nguyễn Văn Bình', 'Trịnh Văn Căn', 'Nguyễn Khắc Ngữ'],
    correct: 0,
    explanation: 'Giám mục Nguyễn Bá Tòng (1868–1949) là giám mục người Việt đầu tiên, tấn phong năm 1933 làm Giám mục Phát Diệm — mốc lịch sử quan trọng của GHCGVN.',
    category: 'cong-giao',
    difficulty: 'medium',
  },
  {
    id: 41,
    question: 'Dòng Tên (Society of Jesus / Jesuit) được ai thành lập và năm nào?',
    answers: ['Phanxicô Assisi, 1209', 'Inhaxiô Loyola, 1540', 'Đaminh, 1216', 'Bênêđictô, 529'],
    correct: 1,
    explanation: 'Dòng Tên do thánh Inhaxiô Loyola thành lập năm 1540, được Giáo hoàng Phaolô III phê chuẩn. Dòng Tên tiên phong truyền đạo tại Việt Nam (thế kỷ XVI–XVII).',
    category: 'cong-giao',
    difficulty: 'medium',
  },
  {
    id: 42,
    question: 'Trung tâm hành hương Công giáo lớn nhất Việt Nam hiện nay là?',
    answers: ['La Vang, Quảng Trị', 'Phát Diệm, Ninh Bình', 'Bãi Dâu, Vũng Tàu', 'Đức Mẹ Tàpao, Bình Thuận'],
    correct: 0,
    explanation: 'La Vang (Quảng Trị) — nơi Đức Mẹ hiện ra năm 1798 — là trung tâm hành hương lớn nhất VN, thu hút hàng triệu tín hữu mỗi năm.',
    category: 'cong-giao',
    difficulty: 'easy',
  },
  {
    id: 43,
    question: 'Nhà thờ Phát Diệm (Ninh Bình) nổi tiếng vì điều gì?',
    answers: [
      'Là nhà thờ lớn nhất VN',
      'Kiến trúc kết hợp Công giáo và đình chùa Việt Nam',
      'Do người Pháp xây dựng',
      'Có chuông lớn nhất Đông Nam Á',
    ],
    correct: 1,
    explanation: 'Phát Diệm (xây 1891–1898 do LM Trần Lục) nổi tiếng với kiến trúc Công giáo kết hợp đình chùa Việt — biểu tượng hội nhập văn hóa của GHCGVN.',
    category: 'cong-giao',
    difficulty: 'medium',
  },
  {
    id: 44,
    question: 'Số lượng tín đồ Công giáo tại Việt Nam hiện nay khoảng bao nhiêu?',
    answers: ['3 triệu', '5 triệu', '7 triệu', '10 triệu'],
    correct: 2,
    explanation: 'VN có khoảng 7 triệu tín đồ Công giáo (~7% dân số), phân bổ nhiều ở TP HCM, Đồng Nai, Hà Nội, Nghệ An — đứng thứ 2 Đông Nam Á sau Philippines.',
    category: 'cong-giao',
    difficulty: 'easy',
  },
  {
    id: 45,
    question: 'Pigneau de Béhaine (Bá Đa Lộc) có vai trò gì trong lịch sử VN?',
    answers: [
      'Người đầu tiên truyền đạo ở VN',
      'Giúp Nguyễn Ánh ký Hiệp ước Versailles 1787, tạo tiền đề can thiệp của Pháp',
      'Biên soạn từ điển tiếng Việt',
      'Xây nhà thờ Đức Bà Sài Gòn',
    ],
    correct: 1,
    explanation: 'Giám mục Bá Đa Lộc (1741–1799) giúp Nguyễn Ánh ký Hiệp ước Versailles (1787) và chiêu mộ cố vấn quân sự phương Tây — tạo tiền đề cho sự can thiệp của Pháp vào VN.',
    category: 'cong-giao',
    difficulty: 'hard',
  },
  {
    id: 46,
    question: 'Hai giáo phận đầu tiên của Công giáo tại Việt Nam (1659) là?',
    answers: ['Đàng Trong và Đàng Ngoài', 'Hà Nội và Sài Gòn', 'Huế và Bắc Ninh', 'Phát Diệm và Vinh'],
    correct: 0,
    explanation: 'Năm 1659, Tòa Thánh thành lập 2 giáo phận: Đàng Ngoài (miền Bắc) và Đàng Trong (miền Nam) — đặt nền tảng cho hàng giáo phẩm Công giáo VN.',
    category: 'cong-giao',
    difficulty: 'hard',
  },
  {
    id: 47,
    question: 'Thánh lễ Misa (Mass) trong Công giáo kỷ niệm điều gì?',
    answers: [
      'Giáng sinh của Chúa Giêsu',
      'Bữa Tiệc Ly và sự hy sinh của Chúa Giêsu',
      'Sự phục sinh của Chúa Giêsu',
      'Lễ Hiện Xuống (Pentecost)',
    ],
    correct: 1,
    explanation: 'Thánh lễ Misa tái hiện Bữa Tiệc Ly — đêm trước khi Chúa Giêsu bị đóng đinh, Ngài lập bí tích Thánh Thể. Đây là trung tâm của thờ phụng Công giáo.',
    category: 'cong-giao',
    difficulty: 'medium',
  },
  // Mác-Lênin mở rộng
  {
    id: 48,
    question: 'Mác và Ăng-ghen viết "Tuyên ngôn Đảng Cộng sản" vào năm nào?',
    answers: ['1840', '1848', '1867', '1871'],
    correct: 1,
    explanation: '"Tuyên ngôn Đảng Cộng sản" (Communist Manifesto) được viết năm 1848 — văn kiện chính trị quan trọng nhất của chủ nghĩa cộng sản.',
    category: 'mac-lenin',
    difficulty: 'easy',
  },
  {
    id: 49,
    question: 'Câu nói của Mác "Tôn giáo là thuốc phiện của nhân dân" có ý nghĩa gì?',
    answers: [
      'Tôn giáo là xấu xa và cần xóa bỏ ngay lập tức',
      'Tôn giáo an ủi người khổ nhưng cũng che lấp áp bức, cần giải phóng qua cách mạng xã hội',
      'Tôn giáo gây nghiện và nguy hiểm như ma túy',
      'Tất cả người theo tôn giáo đều bị lừa dối',
    ],
    correct: 1,
    explanation: 'Mác: tôn giáo như "thuốc phiện" — an ủi người khổ (mặt tích cực) nhưng làm họ chấp nhận khổ đau thay vì đấu tranh (mặt tiêu cực). Giải phóng tôn giáo bắt đầu từ giải phóng xã hội.',
    category: 'mac-lenin',
    difficulty: 'hard',
  },
  {
    id: 50,
    question: 'Theo chủ nghĩa Mác-Lênin, nguồn gốc nhận thức của tôn giáo là gì?',
    answers: [
      'Con người sợ hãi trước thiên nhiên',
      'Sự tuyệt đối hóa, thần thánh hóa nhận thức có giới hạn của con người',
      'Nhu cầu tinh thần của con người',
      'Sự áp bức của giai cấp thống trị',
    ],
    correct: 1,
    explanation: 'Nguồn gốc nhận thức: con người tuyệt đối hóa, thần thánh hóa những mặt hạn chế của nhận thức, biến chúng thành đối tượng thờ cúng khi chưa giải thích được bằng khoa học.',
    category: 'mac-lenin',
    difficulty: 'medium',
  },
  {
    id: 51,
    question: 'Lênin viết tác phẩm "Chủ nghĩa xã hội và tôn giáo" vào năm nào?',
    answers: ['1901', '1905', '1909', '1917'],
    correct: 1,
    explanation: 'Lênin viết "Chủ nghĩa xã hội và tôn giáo" (1905), phân tích quan hệ giữa đảng cộng sản và tôn giáo, nhấn mạnh tôn giáo là "việc riêng" đối với nhà nước.',
    category: 'mac-lenin',
    difficulty: 'hard',
  },
  {
    id: 52,
    question: 'Theo Mác-Lênin, tôn giáo sẽ "tiêu vong" khi nào?',
    answers: [
      'Khi có đủ giáo dục khoa học',
      'Khi nhà nước vô sản cấm tôn giáo',
      'Khi điều kiện kinh tế-xã hội sinh ra tôn giáo không còn tồn tại',
      'Ngay sau cuộc cách mạng vô sản thành công',
    ],
    correct: 2,
    explanation: 'Mác-Lênin: tôn giáo tiêu vong tự nhiên khi điều kiện KT-XH sinh ra nó (áp bức, bất công, bí ẩn tự nhiên) được xóa bỏ trong chủ nghĩa cộng sản — không phải bằng mệnh lệnh hành chính.',
    category: 'mac-lenin',
    difficulty: 'medium',
  },
  {
    id: 53,
    question: 'Đảng CSVN giải quyết vấn đề tôn giáo theo nguyên tắc nào?',
    answers: [
      'Loại trừ tôn giáo khỏi đời sống xã hội',
      'Tôn trọng tự do tín ngưỡng, đoàn kết tôn giáo, phân biệt tín ngưỡng với lợi dụng tôn giáo',
      'Đặt tôn giáo dưới sự lãnh đạo trực tiếp của Đảng',
      'Chỉ công nhận các tôn giáo có trên 1 triệu tín đồ',
    ],
    correct: 1,
    explanation: 'Chính sách tôn giáo ĐCSVN: tôn trọng tự do tín ngưỡng; đoàn kết lương-giáo; phân biệt hoạt động tôn giáo hợp pháp với lợi dụng tôn giáo chống phá chế độ.',
    category: 'mac-lenin',
    difficulty: 'medium',
  },
  {
    id: 54,
    question: 'Hồ Chí Minh coi tôn giáo như thế nào trong sự nghiệp cách mạng?',
    answers: [
      'Là trở ngại cần khắc phục trong xây dựng CNXH',
      'Là lực lượng cần đoàn kết trong mặt trận dân tộc thống nhất',
      'Cần tách biệt hoàn toàn khỏi chính trị',
      'Chỉ có vai trò văn hóa thuần túy',
    ],
    correct: 1,
    explanation: 'Hồ Chí Minh coi đồng bào tôn giáo là lực lượng trong mặt trận đoàn kết dân tộc, áp dụng linh hoạt nguyên tắc Mác-Lênin vào điều kiện VN — "đoàn kết lương giáo".',
    category: 'mac-lenin',
    difficulty: 'medium',
  },
  {
    id: 55,
    question: 'Tính "chính trị" của tôn giáo theo Mác-Lênin biểu hiện như thế nào?',
    answers: [
      'Tôn giáo tham gia tranh cử chính trị',
      'Tôn giáo phản ánh tâm tư, nguyện vọng của tầng lớp nhân dân và đấu tranh giai cấp',
      'Lãnh đạo tôn giáo đồng thời là chính trị gia',
      'Tôn giáo có quân đội và lãnh thổ riêng',
    ],
    correct: 1,
    explanation: 'Tính chính trị: tôn giáo phản ánh ý thức hệ của các giai cấp, có thể bị lợi dụng trong đấu tranh giai cấp — đặt ra yêu cầu quản lý nhà nước về tôn giáo.',
    category: 'mac-lenin',
    difficulty: 'hard',
  },
  // Pháp luật mở rộng
  {
    id: 56,
    question: 'Nghị định 162/2017/NĐ-CP quy định về điều gì?',
    answers: [
      'Xử phạt vi phạm hành chính trong lĩnh vực tôn giáo',
      'Chi tiết thi hành Luật Tín ngưỡng, tôn giáo 2016',
      'Đăng ký hoạt động tôn giáo lần đầu',
      'Quản lý tài sản của tổ chức tôn giáo',
    ],
    correct: 1,
    explanation: 'Nghị định 162/2017/NĐ-CP hướng dẫn thi hành Luật Tín ngưỡng, tôn giáo 2016 — cụ thể hóa quy trình đăng ký, công nhận tổ chức tôn giáo và hoạt động tôn giáo.',
    category: 'phap-luat',
    difficulty: 'hard',
  },
  {
    id: 57,
    question: 'Cơ quan nhà nước chuyên trách quản lý tôn giáo ở Việt Nam hiện nay là?',
    answers: [
      'Bộ Văn hóa, Thể thao và Du lịch',
      'Ban Tôn giáo Chính phủ (thuộc Bộ Nội vụ)',
      'Ủy ban Nhà nước về tôn giáo trực thuộc Thủ tướng',
      'Bộ Ngoại giao',
    ],
    correct: 1,
    explanation: 'Ban Tôn giáo Chính phủ (trực thuộc Bộ Nội vụ) là cơ quan chuyên trách quản lý nhà nước về tôn giáo, tham mưu cho Chính phủ về chính sách tôn giáo.',
    category: 'phap-luat',
    difficulty: 'medium',
  },
  {
    id: 58,
    question: 'Điều kiện để được công nhận là tổ chức tôn giáo theo Luật Tín ngưỡng, tôn giáo 2016?',
    answers: [
      'Chỉ cần có 1.000 tín đồ đăng ký',
      'Hoạt động ổn định từ 5 năm sau đăng ký, tín đồ tự nguyện, có hiến chương và người đại diện hợp pháp',
      'Được Quốc hội phê duyệt theo luật riêng',
      'Cần tổ chức tôn giáo quốc tế công nhận',
    ],
    correct: 1,
    explanation: 'Luật 2016 yêu cầu: đã được cấp đăng ký hoạt động ≥5 năm, tín đồ tự nguyện, có giáo lý/giáo luật rõ ràng, hiến chương và người đại diện có năng lực hành vi dân sự đầy đủ.',
    category: 'phap-luat',
    difficulty: 'hard',
  },
  {
    id: 59,
    question: 'Nhà nước Việt Nam công nhận bao nhiêu tổ chức tôn giáo tính đến năm 2023?',
    answers: ['16 tổ chức', '36 tổ chức', '43 tổ chức', '56 tổ chức'],
    correct: 1,
    explanation: 'Tính đến 2023, VN có 36 tổ chức thuộc 16 tôn giáo được Nhà nước công nhận hoặc cấp đăng ký, với khoảng 26,5 triệu tín đồ (chiếm 27% dân số).',
    category: 'phap-luat',
    difficulty: 'medium',
  },
  {
    id: 60,
    question: 'Quyền tự do tín ngưỡng, tôn giáo theo Điều 24 Hiến pháp 2013 có thể bị hạn chế không?',
    answers: [
      'Không, là quyền tuyệt đối không thể hạn chế',
      'Có, khi cần bảo vệ an ninh quốc gia, trật tự xã hội, sức khỏe cộng đồng, quyền người khác',
      'Chỉ có thể hạn chế bằng luật của Quốc hội',
      'Chỉ bị hạn chế trong tình trạng chiến tranh',
    ],
    correct: 1,
    explanation: 'Điều 24 bảo đảm tự do tín ngưỡng nhưng Điều 15 Hiến pháp 2013 quy định quyền có thể bị hạn chế theo luật khi cần thiết vì lý do an ninh quốc gia, trật tự an toàn xã hội, sức khỏe cộng đồng, quyền lợi của người khác.',
    category: 'phap-luat',
    difficulty: 'hard',
  },
]
